spring.application.name=filelink

# ---- MySQL ----
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/filelink_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:root}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# ---- File upload ----
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=1024MB
spring.servlet.multipart.max-request-size=1024MB
server.tomcat.max-http-form-post-size=1073741824
server.tomcat.max-swallow-size=-1

# Directory where uploaded files are physically stored on disk
filelink.upload-dir=${UPLOAD_DIR:./uploads}

# ---- JWT ----
filelink.jwt.secret=${JWT_SECRET:ChangeThisSuperSecretKeyForFileLinkApp1234567890}
filelink.jwt.expiration-ms=604800000

# ---- CORS ----
filelink.cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:5173}

# ---- Server ----
server.port=${PORT:8080}

cloudinary.cloud-name=u4ncperc
cloudinary.api-key=434522542886324
cloudinary.api-secret=5GMhKZ-rUsl4ZbrzQZ5XzKRGxKw